# Generated by Django 5.1.7 on 2025-09-19 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_grado_10_11', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgrado10_11',
            name='estado',
            field=models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado')], default='EN_PROGRESO', max_length=15),
        ),
        migrations.AddField(
            model_name='testgrado10_11',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='testgrado10_11',
            name='fecha_ultima_actividad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testgrado10_11',
            name='respondidas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testgrado10_11',
            name='ultima_pregunta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testgrado10_11',
            name='fecha_realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testgrado10_11',
            name='respuestas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
