# Generated by Django 5.1.7 on 2025-09-26 23:41

import test_grado_10_11.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_grado_10_11', '0002_testgrado10_11_estado_testgrado10_11_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgrado10_11',
            name='respuestas',
            field=test_grado_10_11.models.PassthroughJSONField(blank=True, default=dict),
        ),
    ]
