# Generated by Django 5.1.7 on 2025-09-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_grade_usuario_grade_ref'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='usuario_usuario_groups', related_name='usuario_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='usuario_usuario_user_permissions', related_name='usuario_permissions', to='auth.permission'),
        ),
        migrations.AlterModelTable(
            name='grade',
            table='usuario_grade',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario_usuario',
        ),
    ]
