# Generated by Django 5.1.7 on 2025-09-26 23:29

import test_grado9.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_grado9', '0002_testgrado9_estado_testgrado9_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgrado9',
            name='respuestas',
            field=test_grado9.models.PassthroughJSONField(blank=True, default=dict),
        ),
    ]
