# Generated by Django 5.1.7 on 2025-11-10 03:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_grado9', '0003_alter_testgrado9_respuestas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGrado9Top3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top3_inicial', to='test_grado9.testgrado9')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado9_top3', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Top 3 inicial (Grado 9)',
                'verbose_name_plural': 'Top 3 inicial (Grado 9)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
